### PR TITLE
 Adds visual indication to where the item will be dropped

### PR DESCRIPTION
**Pull request by luistrivelatto**
Hi, have you had any updates on this kind of widget? I was needing something like it so I took the liberty to modify your code to draw a half-visible item showing where the item the user is dragging will be dropped. Unfortunately, while dragging upwards looks ok, it doesn't feel very natural when going downwards. I believe that is due to our expectation changing according to the direction of the dragging: when you're dragging up, you'd expect that, if the dragged item is on top of the area of some other item, it would be dropped above that other item; while when you're dragging down, you'd expect that if the dragged item is on top of the area of some other item, it would dropped below that other item. I don't know if there's a way to fix this using Draggable and DragTarget, but well, I guess this is good enough for me if there's no better solution around (let me know if you found one).

### CODE REVIEW

**Comment by marchampson** [comment]
Hi, thanks for the update. I'm unable to test today but will take a look tomorrow and hopefully just merge your PR. This was a first stab at doing drag and drop. There are other examples now that constantly update state every time you move they add remove items from the array. I'm undecided on the best approach.

**Comment by marchampson** [comment]
Hi @luistrivelatto could you please check your code again. I've checked out your branch it won't run for me:
I/flutter (24567): The following assertion was thrown building DragTarget<int>(dirty, state:
I/flutter (24567): _DragTargetState<int>#3a6bb):
I/flutter (24567): Failed assertion: boolean expression must not be null

Could you also remove your pubspec.lock file from the commit, as long as I can checkout the update into a clean version of the original and it runs, I'm happy to merge. 

Thanks

**Comment by luistrivelatto** [comment]
I believe it should work now.

Another thing I've realized which has an unnatural feel is when dragging an item in a list long enough to be scrollable. You'd expect that 'pushing' the item towards the top or bottom of the list would make it scroll. I guess this can be fixed by messing around with the ListView's ScrollController or ScrollPhysics, but I'm not familiar with those and couldn't get anything.

**Comment by marchampson** [comment]
Thanks, all merged now. I agree it needs more work, but have had to put on the back burner for a while. If you get the chance to look into it further please feel free to open another pull request :)

**Pull request merged**
